services:
  storage:
    image: jpkitt/storage:latest
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - file_storage:/data/files
    depends_on:
      mongodb:
        condition: service_started
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/mongodb
    restart: unless-stopped
volumes:
  mongodb_data:
  file_storage: